### PR TITLE
feat: add docker

### PR DESCRIPTION
**Pull request by onyxhat**
- create dockerfile
- use multistage
- use distroless

### CODE REVIEW

**Comment by svedova** [comment]
@onyxhat thanks a lot for the PR! 

Can you please update the `README.md` file (perhaps under the Local development section) and add the steps to run Docker? 

I tried the following:

```
$ docker build -t mailer .
$ docker run -t mailer
```

It starts listening but I think it's not accessible from the HOST. I remember there is a setting for that somewhere to create a bridge. 

Also, when I follow the steps above I can't quit the process when I hit `Control + C` 🤔

**Edit** 

OK I had to do portbinding for local development: 

```
docker run -p "5173:5173" -t mailer
```

I'm now trying to understand why the process is not exited when I hit `Control + C`.

**Comment by svedova** [comment]
I'll get this merged, it already adds values. 

I'll create an issue for the Signal and also HMR is not working.

**Comment by svedova** [comment]
Updated Readme with the steps and created https://github.com/stormkit-io/mailer/issues/12 to track the signal issue.

**Comment by onyxhat** [comment]
Noticed the same issue with SIGINT being ignored, but didn't have a chance to dig in much. I think it might be something around nodemon, but not sure. 

Didn't give me much of a chance before you figured out your portbinding issue. If you haven't done it already I'll add some documentation around running in docker.

**Comment by svedova** [comment]
> Noticed the same issue with SIGINT being ignored, but didn't have a chance to dig in much. I think it might be something around nodemon, but not sure.
> 
> Didn't give me much of a chance before you figured out your portbinding issue. If you haven't done it already I'll add some documentation around running in docker.

@onyxhat already added some documentation but please feel free to edit it 🙏 

Thanks once again for the PR!

**Pull request merged**
